version: '3.7'
services:

  api:
    build:
      context: ./api
    restart: unless-stopped
    environment:
      - PORT=${API_PORT}
      - VC_REGISTRY=${VC_REGISTRY}
      - PUBLIC_PATH=${FRONTEND_PUBLIC_PATH}
    ports:
      - "${API_PORT}:${API_PORT}"

  frontend:
      build:
        context: ./frontend
        args:
          - PUBLIC_PATH=${FRONTEND_PUBLIC_PATH}
          - NODE_ENV=${NODE_ENV}
          - BASE_URL=${BASE_URL}
      ports:
        - "${FRONTEND_PORT}:80"
      restart: unless-stopped
