version: '3.7'
services:

  api:
    image: ghcr.io/european-epc-competence-center/vc-verifier/vc_verifier_api
    restart: unless-stopped
    environment:
      - PORT=${API_PORT}
      - VC_REGISTRY=${VC_REGISTRY}
    ports:
      - "${API_PORT}:${API_PORT}"


  frontend:
    image: ghcr.io/european-epc-competence-center/vc-verifier/vc_verifier_frontend
    ports:
      - "${FRONTEND_PORT}:80"
    restart: unless-stopped
    environment:
      - VC_REGISTRY=${VC_REGISTRY}
      - PUBLIC_PATH=${FRONTEND_PUBLIC_PATH}
      - NODE_ENV=${NODE_ENV}
      - BASE_URL=${BASE_URL}


