name: Building All Containers

on:
  push:
    branches: [ 'main' ]
    tags:
      - 'v*'
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:

  build_api:
    name: Build api
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Meta API Image
        id: meta_indy_node
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/european-epc-competence-center/vc-verifier/vc_verifier_api
          flavor: |
            suffix=-api,onlatest=true
            latest=auto
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          labels: |
            org.opencontainers.image.title=VC Verifier API
            org.opencontainers.image.description=API Container of the verifiable credential verifier service.
            org.opencontainers.image.vendor=EECC
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          file: api/Dockerfile
          context: ./api
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_indy_node.outputs.tags }}
          labels: ${{ steps.meta_indy_node.outputs.labels }}

